[features]
seeds = true
skip-lint = false

[programs.devnet]
mythos = "9Mo1trt6n5dvx1fE92hBsqiberkdtuVcsajS6iVyS8Mr"

[programs.localnet]
mythos = "9Mo1trt6n5dvx1fE92hBsqiberkdtuVcsajS6iVyS8Mr"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"

[workspace]
members = ["programs/mythos"]
