import * as anchor from "@coral-xyz/anchor";
import { Program } from "@coral-xyz/anchor";
import {
  Keypair,
  PublicKey,
  SystemProgram,
  SYSVAR_RENT_PUBKEY,
} from "@solana/web3.js";
import {
  TOKEN_PROGRAM_ID,
  createMint,
  createAccount,
  mintTo,
  getAccount,
} from "@solana/spl-token";
import { assert } from "chai";

// Import the IDL type — generated by `anchor build`
import { Mythos } from "../target/types/mythos";

describe("mythos", () => {
  const provider = anchor.AnchorProvider.env();
  anchor.setProvider(provider);

  const program = anchor.workspace.Mythos as Program<Mythos>;

  // Keypairs
  const admin = provider.wallet as anchor.Wallet;
  const borrower = Keypair.generate();
  const lender = Keypair.generate();
  const treasury = Keypair.generate();

  // Mints
  let collateralMint: PublicKey;
  let stablecoinMint: PublicKey;

  // Token accounts
  let borrowerCollateralAta: PublicKey;
  let borrowerStablecoinAta: PublicKey;
  let lenderStablecoinAta: PublicKey;
  let lenderCollateralAta: PublicKey; // for liquidation test

  // PDAs
  let protocolPda: PublicKey;
  let protocolBump: number;

  // Loan params
  const loanId = new anchor.BN(1);
  const principal = new anchor.BN(1_000_000); // 1 USDC (6 decimals)
  const interestRateBps = 750; // 7.5%
  const termSeconds = new anchor.BN(86400 * 30); // 30 days
  const collateralAmount = new anchor.BN(1_500_000); // 1.5x collateral

  before(async () => {
    // Airdrop SOL to borrower and lender
    const airdropBorrower = await provider.connection.requestAirdrop(
      borrower.publicKey,
      5 * anchor.web3.LAMPORTS_PER_SOL,
    );
    await provider.connection.confirmTransaction(airdropBorrower);

    const airdropLender = await provider.connection.requestAirdrop(
      lender.publicKey,
      5 * anchor.web3.LAMPORTS_PER_SOL,
    );
    await provider.connection.confirmTransaction(airdropLender);

    // Create collateral mint (simulates wSOL or any SPL token)
    collateralMint = await createMint(
      provider.connection,
      (admin as any).payer,
      admin.publicKey,
      null,
      6, // 6 decimals
    );

    // Create stablecoin mint (simulates USDC)
    stablecoinMint = await createMint(
      provider.connection,
      (admin as any).payer,
      admin.publicKey,
      null,
      6, // 6 decimals
    );

    // Create token accounts
    borrowerCollateralAta = await createAccount(
      provider.connection,
      (admin as any).payer,
      collateralMint,
      borrower.publicKey,
    );

    borrowerStablecoinAta = await createAccount(
      provider.connection,
      (admin as any).payer,
      stablecoinMint,
      borrower.publicKey,
    );

    lenderStablecoinAta = await createAccount(
      provider.connection,
      (admin as any).payer,
      stablecoinMint,
      lender.publicKey,
    );

    lenderCollateralAta = await createAccount(
      provider.connection,
      (admin as any).payer,
      collateralMint,
      lender.publicKey,
    );

    // Mint collateral to borrower (for deposit)
    await mintTo(
      provider.connection,
      (admin as any).payer,
      collateralMint,
      borrowerCollateralAta,
      admin.publicKey,
      2_000_000, // 2.0 tokens
    );

    // Mint stablecoin to lender (for funding the loan)
    await mintTo(
      provider.connection,
      (admin as any).payer,
      stablecoinMint,
      lenderStablecoinAta,
      admin.publicKey,
      5_000_000, // 5.0 USDC
    );

    // Mint stablecoin to borrower (for repayment = principal + interest)
    await mintTo(
      provider.connection,
      (admin as any).payer,
      stablecoinMint,
      borrowerStablecoinAta,
      admin.publicKey,
      2_000_000, // 2.0 USDC (enough for principal + interest)
    );

    // Derive protocol PDA
    [protocolPda, protocolBump] = PublicKey.findProgramAddressSync(
      [Buffer.from("protocol")],
      program.programId,
    );
  });

  it("initializes protocol", async () => {
    const tx = await program.methods
      .initializeProtocol(15000, 12000) // 150% collateral, 120% liquidation
      .accounts({
        admin: admin.publicKey,
        protocolState: protocolPda,
        treasury: treasury.publicKey,
        systemProgram: SystemProgram.programId,
      })
      .rpc();

    console.log("  ✅ initialize_protocol tx:", tx);

    const protocol = await program.account.protocolState.fetch(protocolPda);
    assert.equal(protocol.admin.toBase58(), admin.publicKey.toBase58());
    assert.equal(protocol.minCollateralRatioBps, 15000);
    assert.equal(protocol.liquidationThresholdBps, 12000);
    assert.equal(protocol.loanCount.toNumber(), 0);
  });

  it("initializes a loan", async () => {
    const loanIdBytes = loanId.toArrayLike(Buffer, "le", 8);
    const [loanPda] = PublicKey.findProgramAddressSync(
      [Buffer.from("loan"), borrower.publicKey.toBuffer(), loanIdBytes],
      program.programId,
    );
    const [vaultPda] = PublicKey.findProgramAddressSync(
      [Buffer.from("vault"), loanPda.toBuffer()],
      program.programId,
    );

    const tx = await program.methods
      .initializeLoan(loanId, principal, interestRateBps, termSeconds)
      .accounts({
        borrower: borrower.publicKey,
        loanAccount: loanPda,
        collateralVault: vaultPda,
        protocolState: protocolPda,
        collateralMint: collateralMint,
        stablecoinMint: stablecoinMint,
        tokenProgram: TOKEN_PROGRAM_ID,
        systemProgram: SystemProgram.programId,
        rent: SYSVAR_RENT_PUBKEY,
      })
      .signers([borrower])
      .rpc();

    console.log("  ✅ initialize_loan tx:", tx);

    const loan = await program.account.loanAccount.fetch(loanPda);
    assert.equal(loan.borrower.toBase58(), borrower.publicKey.toBase58());
    assert.equal(loan.principal.toNumber(), 1_000_000);
    assert.equal(loan.interestRateBps, 750);
    assert.deepEqual(loan.status, { requested: {} });

    // Verify protocol loan count incremented
    const protocol = await program.account.protocolState.fetch(protocolPda);
    assert.equal(protocol.loanCount.toNumber(), 1);
  });

  it("deposits collateral", async () => {
    const loanIdBytes = loanId.toArrayLike(Buffer, "le", 8);
    const [loanPda] = PublicKey.findProgramAddressSync(
      [Buffer.from("loan"), borrower.publicKey.toBuffer(), loanIdBytes],
      program.programId,
    );
    const [vaultPda] = PublicKey.findProgramAddressSync(
      [Buffer.from("vault"), loanPda.toBuffer()],
      program.programId,
    );

    const tx = await program.methods
      .depositCollateral(collateralAmount)
      .accounts({
        borrower: borrower.publicKey,
        loanAccount: loanPda,
        borrowerCollateralAta: borrowerCollateralAta,
        collateralVault: vaultPda,
        tokenProgram: TOKEN_PROGRAM_ID,
      })
      .signers([borrower])
      .rpc();

    console.log("  ✅ deposit_collateral tx:", tx);

    const loan = await program.account.loanAccount.fetch(loanPda);
    assert.equal(loan.collateralAmount.toNumber(), 1_500_000);

    // Verify vault balance
    const vaultAccount = await getAccount(provider.connection, vaultPda);
    assert.equal(Number(vaultAccount.amount), 1_500_000);
  });

  it("funds the loan (lender → borrower)", async () => {
    const loanIdBytes = loanId.toArrayLike(Buffer, "le", 8);
    const [loanPda] = PublicKey.findProgramAddressSync(
      [Buffer.from("loan"), borrower.publicKey.toBuffer(), loanIdBytes],
      program.programId,
    );

    const borrowerBalanceBefore = await getAccount(
      provider.connection,
      borrowerStablecoinAta,
    );

    const tx = await program.methods
      .fundLoan()
      .accounts({
        lender: lender.publicKey,
        loanAccount: loanPda,
        protocolState: protocolPda,
        lenderStablecoinAta: lenderStablecoinAta,
        borrowerStablecoinAta: borrowerStablecoinAta,
        tokenProgram: TOKEN_PROGRAM_ID,
      })
      .signers([lender])
      .rpc();

    console.log("  ✅ fund_loan tx:", tx);

    const loan = await program.account.loanAccount.fetch(loanPda);
    assert.equal(loan.lender.toBase58(), lender.publicKey.toBase58());
    assert.deepEqual(loan.status, { active: {} });
    assert.ok(loan.startTime.toNumber() > 0);

    // Verify borrower received the principal
    const borrowerBalanceAfter = await getAccount(
      provider.connection,
      borrowerStablecoinAta,
    );
    assert.equal(
      Number(borrowerBalanceAfter.amount) -
        Number(borrowerBalanceBefore.amount),
      1_000_000,
    );
  });

  it("repays the loan (borrower → lender, collateral returned)", async () => {
    const loanIdBytes = loanId.toArrayLike(Buffer, "le", 8);
    const [loanPda] = PublicKey.findProgramAddressSync(
      [Buffer.from("loan"), borrower.publicKey.toBuffer(), loanIdBytes],
      program.programId,
    );
    const [vaultPda] = PublicKey.findProgramAddressSync(
      [Buffer.from("vault"), loanPda.toBuffer()],
      program.programId,
    );

    const lenderBalanceBefore = await getAccount(
      provider.connection,
      lenderStablecoinAta,
    );

    const tx = await program.methods
      .repayLoan()
      .accounts({
        borrower: borrower.publicKey,
        loanAccount: loanPda,
        borrowerStablecoinAta: borrowerStablecoinAta,
        lenderStablecoinAta: lenderStablecoinAta,
        collateralVault: vaultPda,
        borrowerCollateralAta: borrowerCollateralAta,
        tokenProgram: TOKEN_PROGRAM_ID,
      })
      .signers([borrower])
      .rpc();

    console.log("  ✅ repay_loan tx:", tx);

    const loan = await program.account.loanAccount.fetch(loanPda);
    assert.deepEqual(loan.status, { repaid: {} });
    assert.equal(loan.collateralAmount.toNumber(), 0);

    // Verify lender received principal + interest
    // Interest = 1_000_000 * 750 / 10000 = 75_000
    const lenderBalanceAfter = await getAccount(
      provider.connection,
      lenderStablecoinAta,
    );
    const lenderReceived =
      Number(lenderBalanceAfter.amount) - Number(lenderBalanceBefore.amount);
    assert.equal(lenderReceived, 1_075_000); // 1M principal + 75K interest

    // Verify borrower got collateral back
    const borrowerCollateral = await getAccount(
      provider.connection,
      borrowerCollateralAta,
    );
    assert.equal(Number(borrowerCollateral.amount), 2_000_000); // original 2M minus 1.5M deposited + 1.5M returned

    // Verify vault is empty
    const vaultAccount = await getAccount(provider.connection, vaultPda);
    assert.equal(Number(vaultAccount.amount), 0);

    console.log("\n  🎉 Full loan lifecycle complete!");
    console.log("  Principal: 1.0 USDC");
    console.log("  Interest: 0.075 USDC (7.5%)");
    console.log("  Collateral: 1.5 USDC (returned to borrower)");
  });
});
